--- Psychonauts 2 Archipelago Mod — Item Table & Grant Functions
--- Auto-generated from Psychonauts_2_Item_List.csv
--- Generated by the same disambiguation logic as the Python world (items.py).
---
--- Maps AP item IDs to display names and in-game grant functions.
--- Item ID base: 7792462
---
--- DISPLAY NAME DEDUPLICATION:
---   When the source CSV contains multiple items with identical base names,
---   a type suffix (e.g. "(Half-a-Mind)", "(Purse Tag)") is appended, matching
---   the logic in Python items.py _item_type_suffix_from_key().  Items that
---   still share a display name after disambiguation are treated as copies of
---   the same AP item and share the first occurrence's ID.
---
--- PROGRESSIVE ITEMS:
---   Eight psychic abilities and three inventory-upgrade pairs are progressive.
---   Finding any copy advances the player one tier.  The grant function tracks
---   the current tier in the AP save state.
---
--- UE4 blueprint paths used (Psychonauts 2, UE 4.26):
---   Player character:   /Game/Characters/Raz/BP_Raz.BP_Raz_C
---   Game instance:      Psychonauts2GameInstance_C
---   Ability component:  PsychicsComponent (on BP_Raz_C)
---   Inventory component:InventoryComponent (on BP_Raz_C)

local Items = {}

-- ---------------------------------------------------------------------------
-- AP item ID → display name
-- ---------------------------------------------------------------------------
-- Only one entry per unique display name.  The AP server only sends IDs that
-- appear here; duplicate-named items in the CSV share the first ID.

Items.id_to_name = {
    [7792462] = "Motherlobe Psi Card 1",  -- ML_PsiCard1
    [7792463] = "Motherlobe Psi Card 2",  -- ML_PsiCard2
    [7792464] = "Motherlobe Psi Card 3",  -- ML_PsiCard3
    [7792465] = "Motherlobe Psi Card 4",  -- ML_PsiCard4
    [7792466] = "Motherlobe Psi Card 5",  -- ML_PsiCard5
    [7792467] = "Motherlobe Psi Card 6",  -- ML_PsiCard6
    [7792468] = "Motherlobe Psi Card 7",  -- ML_PsiCard7
    [7792469] = "Motherlobe Psi Card 8",  -- ML_PsiCard8
    [7792470] = "Motherlobe Psi Card 9",  -- ML_PsiCard9
    [7792471] = "Motherlobe Psi Card 10",  -- ML_PsiCard10
    [7792472] = "Motherlobe Psi Card 11",  -- ML_PsiCard11
    [7792473] = "Motherlobe Psi Card 12",  -- ML_PsiCard12
    [7792474] = "Motherlobe Psi Card 13",  -- ML_PsiCard13
    [7792475] = "Motherlobe Psi Card 14",  -- ML_PsiCard14
    [7792476] = "Motherlobe Psi Card 15",  -- ML_PsiCard15
    [7792477] = "Motherlobe Psi Card 16",  -- ML_PsiCard16
    [7792478] = "Motherlobe Psi Card 17",  -- ML_PsiCard17
    [7792479] = "Motherlobe Psi Card 18",  -- ML_PsiCard18
    [7792480] = "Motherlobe Psi Card 19",  -- ML_PsiCard19
    [7792481] = "Motherlobe Psi Card 20",  -- ML_PsiCard20
    [7792482] = "Motherlobe Psi Card 21",  -- ML_PsiCard21
    [7792483] = "Motherlobe Psi Card 22",  -- ML_PsiCard22
    [7792484] = "Motherlobe Psi Card 23",  -- ML_PsiCard23
    [7792485] = "Motherlobe Psi Card 24",  -- ML_PsiCard24
    [7792486] = "Motherlobe Psi Card 25",  -- ML_PsiCard25
    [7792487] = "Motherlobe Psi Card 26",  -- ML_PsiCard26
    [7792488] = "Motherlobe Psi Card 27",  -- ML_PsiCard27
    [7792489] = "Motherlobe Supply Chest 1",  -- ML_SupplyChests1
    [7792490] = "Motherlobe Supply Chest 2",  -- ML_SupplyChests2
    [7792491] = "Motherlobe Supply Chest 3",  -- ML_SupplyChests3
    [7792492] = "Motherlobe Supply Chest 4",  -- ML_SupplyChests4
    [7792493] = "Motherlobe Supply Chest 5",  -- ML_SupplyChests5
    [7792494] = "Motherlobe Supply Chest 6",  -- ML_SupplyChests6
    [7792495] = "Motherlobe Supply Chest Key 1",  -- ML_SupplyKey1
    [7792496] = "Motherlobe Supply Chest Key 2",  -- ML_SupplyKey2
    [7792497] = "Motherlobe Supply Chest Key 3",  -- ML_SupplyKey3
    [7792498] = "Motherlobe Supply Chest Key 4",  -- ML_SupplyKey4
    [7792499] = "Motherlobe Supply Chest Key 5",  -- ML_SupplyKey5
    [7792500] = "Motherlobe Supply Chest Key 6",  -- ML_SupplyKey6
    [7792501] = "Motherlobe Psy Challenge Markers 1",  -- ML_PsyChallengeMarkers1
    [7792502] = "Motherlobe Psy Challenge Markers 2",  -- ML_PsyChallengeMarkers2
    [7792503] = "Motherlobe Psy Challenge Markers 3",  -- ML_PsyChallengeMarkers3
    [7792504] = "Motherlobe Psy Challenge Markers 4",  -- ML_PsyChallengeMarkers4
    [7792505] = "Motherlobe Psy Challenge Markers 5",  -- ML_PsyChallengeMarkers5
    [7792506] = "Motherlobe Psy Challenge Markers 6",  -- ML_PsyChallengeMarkers6
    [7792507] = "Motherlobe Psy Challenge Markers 7",  -- ML_PsyChallengeMarkers7
    [7792508] = "Motherlobe Psy Challenge Markers 8",  -- ML_PsyChallengeMarkers8
    [7792509] = "Day Old Sushi",  -- DayOldSushi
    [7792510] = "Enemy Surveillance Device",  -- EnemySurveillanceDevice
    [7792511] = "Name Plaque",  -- NamePlaque
    [7792512] = "Deck of Cards",  -- DeckOfCards
    [7792513] = "Astronaut Ice Cream",  -- AstronautIceCream
    [7792514] = "Tried and True",  -- Classic_Outfit
    [7792515] = "Circus Skivvies",  -- Circus_Outfit
    [7792516] = "Suit",  -- Suit_Outfit
    [7792517] = "Quarry Psi Card 1",  -- Quarry_PsiCard1
    [7792518] = "Quarry Psi Card 2",  -- Quarry_PsiCard2
    [7792519] = "Quarry Psi Card 3",  -- Quarry_PsiCard3
    [7792520] = "Quarry Psi Card 4",  -- Quarry_PsiCard4
    [7792521] = "Quarry Psi Card 5",  -- Quarry_PsiCard5
    [7792522] = "Quarry Psi Card 6",  -- Quarry_PsiCard6
    [7792523] = "Quarry Psi Card 7",  -- Quarry_PsiCard7
    [7792524] = "Quarry Psi Card 8",  -- Quarry_PsiCard8
    [7792525] = "Quarry Psi Card 9",  -- Quarry_PsiCard9
    [7792526] = "Quarry Psi Card 10",  -- Quarry_PsiCard10
    [7792527] = "Quarry Psi Card 11",  -- Quarry_PsiCard11
    [7792528] = "Quarry Psi Card 12",  -- Quarry_PsiCard12
    [7792529] = "Quarry Psi Card 13",  -- Quarry_PsiCard13
    [7792530] = "Quarry Psi Card 14",  -- Quarry_PsiCard14
    [7792531] = "Quarry Psi Card 15",  -- Quarry_PsiCard15
    [7792532] = "Quarry Psi Card 16",  -- Quarry_PsiCard16
    [7792533] = "Quarry Psi Card 17",  -- Quarry_PsiCard17
    [7792534] = "Quarry Psi Card 18",  -- Quarry_PsiCard18
    [7792535] = "Quarry Supply Chest 1",  -- Quarry_SupplyChests1
    [7792536] = "Quarry Supply Chest 2",  -- Quarry_SupplyChests2
    [7792537] = "Quarry Supply Chest 3",  -- Quarry_SupplyChests3
    [7792538] = "Quarry Supply Chest 4",  -- Quarry_SupplyChests4
    [7792539] = "Quarry Supply Key 1",  -- Quarry_SupplyKey1
    [7792540] = "Quarry Supply Key 2",  -- Quarry_SupplyKey2
    [7792541] = "Quarry Supply Key 3",  -- Quarry_SupplyKey3
    [7792542] = "Quarry Supply Key 4",  -- Quarry_SupplyKey4
    [7792543] = "Quarry Psy Challenge Marker 1",  -- Quarry_PsyChallengeMarkers1
    [7792544] = "Quarry Psy Challenge Marker 2",  -- Quarry_PsyChallengeMarkers2
    [7792545] = "Quarry Psy Challenge Marker 3",  -- Quarry_PsyChallengeMarkers3
    [7792546] = "Quarry Psy Challenge Marker 4",  -- Quarry_PsyChallengeMarkers4
    [7792547] = "Quarry Psy Challenge Marker 5",  -- Quarry_PsyChallengeMarkers5
    [7792548] = "Agent Orientation Laserdisc",  -- Laserdisc
    [7792549] = "Unexploded Bomb",  -- UnexplodedBomb
    [7792550] = "Psitanium Knife",  -- PsitaniumKnife
    [7792551] = "Empty Jar",  -- Empty_Jar
    [7792552] = "Questionable Area Psi Card 1",  -- QA_PsiCard1
    [7792553] = "Questionable Area Psi Card 2",  -- QA_PsiCard2
    [7792554] = "Questionable Area Psi Card 3",  -- QA_PsiCard3
    [7792555] = "Questionable Area Psi Card 4",  -- QA_PsiCard4
    [7792556] = "Questionable Area Psi Card 5",  -- QA_PsiCard5
    [7792557] = "Questionable Area Psi Card 6",  -- QA_PsiCard6
    [7792558] = "Questionable Area Psi Card 7",  -- QA_PsiCard7
    [7792559] = "Questionable Area Psi Card 8",  -- QA_PsiCard8
    [7792560] = "Questionable Area Psi Card 9",  -- QA_PsiCard9
    [7792561] = "Questionable Area Psi Card 10",  -- QA_PsiCard10
    [7792562] = "Questionable Area Psi Card 11",  -- QA_PsiCard11
    [7792563] = "Questionable Area Psi Card 12",  -- QA_PsiCard12
    [7792564] = "Questionable Area Psi Card 13",  -- QA_PsiCard13
    [7792565] = "Questionable Area Psi Card 14",  -- QA_PsiCard14
    [7792566] = "Questionable Area Psi Card 15",  -- QA_PsiCard15
    [7792567] = "Questionable Area Psi Card 16",  -- QA_PsiCard16
    [7792568] = "Questionable Area Psi Card 17",  -- QA_PsiCard17
    [7792569] = "Questionable Area Psi Card 18",  -- QA_PsiCard18
    [7792570] = "Questionable Area Psi Card 19",  -- QA_PsiCard19
    [7792571] = "Questionable Area Psi Card 20",  -- QA_PsiCard20
    [7792572] = "Questionable Area Psi Card 21",  -- QA_PsiCard21
    [7792573] = "Questionable Area Psi Card 22",  -- QA_PsiCard22
    [7792574] = "Questionable Area Psi Card 23",  -- QA_PsiCard23
    [7792575] = "Questionable Area Psi Card 24",  -- QA_PsiCard24
    [7792576] = "Questionable Area Psi Card 25",  -- QA_PsiCard25
    [7792577] = "Questionable Area Psi Card 26",  -- QA_PsiCard26
    [7792578] = "Questionable Area Psi Card 27",  -- QA_PsiCard27
    [7792579] = "Questionable Area Supply Chest 1",  -- QA_SupplyChests1
    [7792580] = "Questionable Area Supply Chest 2",  -- QA_SupplyChests2
    [7792581] = "Questionable Area Supply Chest 3",  -- QA_SupplyChests3
    [7792582] = "Questionable Area Supply Chest 4",  -- QA_SupplyChests4
    [7792583] = "Questionable Area Supply Chest Key 1",  -- QA_SupplyKey1
    [7792584] = "Questionable Area Supply Chest Key 2",  -- QA_SupplyKey2
    [7792585] = "Questionable Area Supply Chest Key 3",  -- QA_SupplyKey3
    [7792586] = "Questionable Area Supply Chest Key 4",  -- QA_SupplyKey4
    [7792587] = "Questionable Area Psy Challenge Marker 1",  -- QA_PsyChallengeMarkers1
    [7792588] = "Questionable Area Psy Challenge Marker 2",  -- QA_PsyChallengeMarkers2
    [7792589] = "Questionable Area Psy Challenge Marker 3",  -- QA_PsyChallengeMarkers3
    [7792590] = "Questionable Area Psy Challenge Marker 4",  -- QA_PsyChallengeMarkers4
    [7792591] = "Questionable Area Psy Challenge Marker 5",  -- QA_PsyChallengeMarkers5
    [7792592] = "Questionable Area Psy Challenge Marker 6",  -- QA_PsyChallengeMarkers6
    [7792593] = "Questionable Area Psy Challenge Marker 7",  -- QA_PsyChallengeMarkers7
    [7792594] = "Human Skull",  -- Human_Skull
    [7792595] = "Novelty Mug",  -- Novelty_Mug
    [7792596] = "Can of Corn",  -- Can_of_Corn
    [7792597] = "Switchblade Hatchet",  -- Switchblade_Hatchet
    [7792598] = "Lili's Mushroom",  -- Lilis_Mushroom
    [7792599] = "Jar of Bees",  -- Bee_Jar
    [7792600] = "Green Needle Gulch Psi Card 1",  -- GNG_PsiCard1
    [7792601] = "Green Needle Gulch Psi Card 2",  -- GNG_PsiCard2
    [7792602] = "Green Needle Gulch Psi Card 3",  -- GNG_PsiCard3
    [7792603] = "Green Needle Gulch Psi Card 4",  -- GNG_PsiCard4
    [7792604] = "Green Needle Gulch Psi Card 5",  -- GNG_PsiCard5
    [7792605] = "Green Needle Gulch Psi Card 6",  -- GNG_PsiCard6
    [7792606] = "Green Needle Gulch Psi Card 7",  -- GNG_PsiCard7
    [7792607] = "Green Needle Gulch Psi Card 8",  -- GNG_PsiCard8
    [7792608] = "Green Needle Gulch Psi Card 9",  -- GNG_PsiCard9
    [7792609] = "Green Needle Gulch Psi Card 10",  -- GNG_PsiCard10
    [7792610] = "Green Needle Gulch Psi Card 11",  -- GNG_PsiCard11
    [7792611] = "Green Needle Gulch Psi Card 12",  -- GNG_PsiCard12
    [7792612] = "Green Needle Gulch Psi Card 13",  -- GNG_PsiCard13
    [7792613] = "Green Needle Gulch Psi Card 14",  -- GNG_PsiCard14
    [7792614] = "Green Needle Gulch Psi Card 15",  -- GNG_PsiCard15
    [7792615] = "Green Needle Gulch Psi Card 16",  -- GNG_PsiCard16
    [7792616] = "Green Needle Gulch Psi Card 17",  -- GNG_PsiCard17
    [7792617] = "Green Needle Gulch Psi Card 18",  -- GNG_PsiCard18
    [7792618] = "Green Needle Gulch Psi Card 19",  -- GNG_PsiCard19
    [7792619] = "Green Needle Gulch Psi Card 20",  -- GNG_PsiCard20
    [7792620] = "Green Needle Gulch Psi Card 21",  -- GNG_PsiCard21
    [7792621] = "Green Needle Gulch Psi Card 22",  -- GNG_PsiCard22
    [7792622] = "Green Needle Gulch Psi Card 23",  -- GNG_PsiCard23
    [7792623] = "Green Needle Gulch Psi Card 24",  -- GNG_PsiCard24
    [7792624] = "Green Needle Gulch Psi Card 25",  -- GNG_PsiCard25
    [7792625] = "Green Needle Gulch Psi Card 26",  -- GNG_PsiCard26
    [7792626] = "Green Needle Gulch Psi Card 27",  -- GNG_PsiCard27
    [7792627] = "Green Needle Gulch Supply Chests 1",  -- GNG_SupplyChests1
    [7792628] = "Green Needle Gulch Supply Chests 2",  -- GNG_SupplyChests2
    [7792629] = "Green Needle Gulch Supply Chests Key 1",  -- GNG_SupplyKey1
    [7792630] = "Green Needle Gulch Supply Chests Key 2",  -- GNG_SupplyKey2
    [7792631] = "Green Needle Gulch Psy Challenge Marker 1",  -- GNG_PsyChallengeMarkers1
    [7792632] = "Green Needle Gulch Psy Challenge Marker 2",  -- GNG_PsyChallengeMarkers2
    [7792633] = "Green Needle Gulch Psy Challenge Marker 3",  -- GNG_PsyChallengeMarkers3
    [7792634] = "Green Needle Gulch Psy Challenge Marker 4",  -- GNG_PsyChallengeMarkers4
    [7792635] = "Mini Murder Bug Bot",  -- MurderBot
    [7792636] = "Beehive shaped like my phone",  -- Beehive
    [7792637] = "Viking Helmet",  -- VikingHelmet
    [7792638] = "Signed Copy of Mindswarm",  -- Mindswarm
    [7792639] = "Loboto's Labrynth Nugget of Wisdom 1",  -- Loboto_Nugget1
    [7792640] = "Loboto's Labrynth Nugget of Wisdom 2",  -- Loboto_Nugget2
    [7792641] = "Loboto's Labrynth Memory Vault 1",  -- Loboto_MemoryVault1
    [7792642] = "Loboto's Labrynth Memory Vault 2",  -- Loboto_MemoryVault2
    [7792643] = "Loboto's Labrynth Suitcase Tag",  -- Loboto_Suitcase_Tag
    [7792644] = "Loboto's Labrynth Hatbox Tag",  -- Loboto_Hatbox_Tag
    [7792645] = "Loboto's Labrynth Purse Tag",  -- Loboto_Purse_Tag
    [7792646] = "Loboto's Labrynth Steamer Trunk Tag",  -- Loboto_SteamerTrunk_Tag
    [7792647] = "Loboto's Labrynth Dufflebag Tag",  -- Loboto_Dufflebag_Tag
    [7792648] = "Loboto's Labrynth Suitcase",  -- Loboto_Suitcase
    [7792649] = "Loboto's Labrynth Hatbox",  -- Loboto_Hatbox
    [7792650] = "Loboto's Labrynth Purse",  -- Loboto_Purse
    [7792651] = "Loboto's Labrynth Steamer Trunk",  -- Loboto_SteamerTrunk
    [7792652] = "Loboto's Labrynth Dufflebag",  -- Loboto_Dufflebag
    [7792653] = "Hollis' Classroom Nugget of Wisdom 1",  -- HC_Nugget1
    [7792654] = "Hollis' Classroom Nugget of Wisdom 2",  -- HC_Nugget2
    [7792655] = "Hollis' Classroom Nugget of Wisdom 3",  -- HC_Nugget3
    [7792656] = "Hollis' Classroom Half-a-Mind 1",  -- HC_HAM1
    [7792657] = "Hollis' Classroom Half-a-Mind 2",  -- HC_HAM2
    [7792658] = "Hollis' Classroom Memory Vault 1",  -- HC_MemoryVault1
    [7792659] = "Hollis' Classroom Hatbox Tag",  -- HC_Hatbox_Tag
    [7792660] = "Hollis' Classroom Steamer Trunk Tag",  -- HC_SteamerTrunk_Tag
    [7792661] = "Hollis' Classroom Hatbox",  -- HC_Hatbox
    [7792662] = "Hollis' Classroom Steamer Trunk",  -- HC_SteamerTrunk
    [7792663] = "Hollis' Hot Streak Nugget of Wisdom 1",  -- HH_Nugget1
    [7792664] = "Hollis' Hot Streak Nugget of Wisdom 2",  -- HH_Nugget2
    [7792665] = "Hollis' Hot Streak Nugget of Wisdom 3",  -- HH_Nugget3
    [7792666] = "Hollis' Hot Streak Nugget of Wisdom 4",  -- HH_Nugget4
    [7792667] = "Hollis' Hot Streak Half-a-Mind 1",  -- HH_HAM1
    [7792668] = "Hollis' Hot Streak Half-a-Mind 2",  -- HH_HAM2
    [7792669] = "Hollis' Hot Streak Half-a-Mind 3",  -- HH_HAM3
    [7792670] = "Hollis' Hot Streak Half-a-Mind 4",  -- HH_HAM4
    [7792671] = "Hollis' Hot Streak Memory Vault 1",  -- HH_MemoryVault1
    [7792672] = "Hollis' Hot Streak Suitcase Tag",  -- HH_Suitcase_Tag
    [7792673] = "Hollis' Hot Streak Purse Tag",  -- HH_Purse_Tag
    [7792674] = "Hollis' Hot Streak Dufflebag Tag",  -- HH_Dufflebag_Tag
    [7792675] = "Hollis' Hot Streak Suitcase",  -- HH_Suitcase
    [7792676] = "Hollis' Hot Streak Purse",  -- HH_Purse
    [7792677] = "Hollis' Hot Streak Dufflebag",  -- HH_Dufflebag
    [7792678] = "Compton's Cookoff Nugget 1",  -- Compton_Nugget1
    [7792679] = "Compton's Cookoff Nugget 2",  -- Compton_Nugget2
    [7792680] = "Compton's Cookoff Half-a-Mind 1",  -- Compton_HAM1
    [7792681] = "Compton's Cookoff Half-a-Mind 2",  -- Compton_HAM2
    [7792682] = "Compton's Cookoff Memory Vault 1",  -- Compton_MemoryVault1
    [7792683] = "Compton's Cookoff Memory Vault 2",  -- Compton_MemoryVault2
    [7792684] = "Compton's Cookoff Suitcase Tag",  -- Compton_Suitcase_Tag
    [7792685] = "Compton's Cookoff Hatbox Tag",  -- Compton_Hatbox_Tag
    [7792686] = "Compton's Cookoff Purse Tag",  -- Compton_Purse_Tag
    [7792687] = "Compton's Cookoff Steamer Trunk Tag",  -- Compton_SteamerTrunk_Tag
    [7792688] = "Compton's Cookoff Dufflebag Tag",  -- Compton_Dufflebag_Tag
    [7792689] = "Compton's Cookoff Suitcase",  -- Compton_Suitcase
    [7792690] = "Compton's Cookoff Hatbox",  -- Compton_Hatbox
    [7792691] = "Compton's Cookoff Purse",  -- Compton_Purse
    [7792692] = "Compton's Cookoff Steamer Trunk",  -- Compton_SteamerTrunk
    [7792693] = "Compton's Cookoff Dufflebag",  -- Compton_Dufflebag
    [7792694] = "Psi King's Sensorium Nugget of Wisdom 1",  -- PsiKing_Nugget1
    [7792695] = "Psi King's Sensorium Nugget of Wisdom 2",  -- PsiKing_Nugget2
    [7792696] = "Psi King's Sensorium Nugget of Wisdom 3",  -- PsiKing_Nugget3
    [7792697] = "Psi King's Sensorium Half-a-Mind 1",  -- PsiKing_HAM1
    [7792698] = "Psi King's Sensorium Half-a-Mind 2",  -- PsiKing_HAM2
    [7792699] = "Psi King's Sensorium Half-a-Mind 3",  -- PsiKing_HAM3
    [7792700] = "Psi King's Sensorium Half-a-Mind 4",  -- PsiKing_HAM4
    [7792701] = "Psi King's Sensorium Memory Vault 1",  -- PsiKing_MemoryVault1
    [7792702] = "Psi King's Sensorium Memory Vault 2",  -- PsiKing_MemoryVault2
    [7792703] = "Psi King's Sensorium Suitcase Tag",  -- PsiKing_Suitcase_Tag
    [7792704] = "Psi King's Sensorium Hatbox Tag",  -- PsiKing_Hatbox_Tag
    [7792705] = "Psi King's Sensorium Purse Tag",  -- PsiKing_Purse_Tag
    [7792706] = "Psi King's Sensorium Steamer Trunk Tag",  -- PsiKing_SteamerTrunk_Tag
    [7792707] = "Psi King's Sensorium Dufflebag Tag",  -- PsiKing_Dufflebag_Tag
    [7792708] = "Psi King's Sensorium Suitcase",  -- PsiKing_Suitcase
    [7792709] = "Psi King's Sensorium Hatbox",  -- PsiKing_Hatbox
    [7792710] = "Psi King's Sensorium Purse",  -- PsiKing_Purse
    [7792711] = "Psi King's Sensorium Steamer Trunk",  -- PsiKing_SteamerTrunk
    [7792712] = "Psi King's Sensorium Dufflebag",  -- PsiKing_Dufflebag
    [7792713] = "Ford's Follicles Nugget of Wisdom 1",  -- Ford_Nugget1
    [7792714] = "Ford's Follicles Half-a-Mind 1",  -- Ford_HAM1
    [7792715] = "Ford's Follicles Memory Vault 1",  -- Ford_MemoryVault1
    [7792716] = "Ford's Follicles Steamer Trunk Tag",  -- Ford_SteamerTrunk_Tag
    [7792717] = "Ford's Follicles Steamer Trunk",  -- Ford_SteamerTrunk
    [7792718] = "Strike City Nugget of Wisdom 1",  -- StrikeCity_Nugget1
    [7792719] = "Strike City Half-a-Mind 1",  -- StrikeCity_HAM1
    [7792720] = "Strike City Memory Vault 1",  -- StrikeCity_MemoryVault1
    [7792721] = "Strike City Suitcase Tag",  -- StrikeCity_Suitcase_Tag
    [7792722] = "Strike City Dufflebag Tag",  -- StrikeCity_Dufflebag_Tag
    [7792723] = "Strike City Suitcase",  -- StrikeCity_Suitcase
    [7792724] = "Strike City Dufflebag",  -- StrikeCity_Dufflebag
    [7792725] = "Cruller's Correspondence Nugget of Wisdom 1",  -- Cruller_Nugget1
    [7792726] = "Cruller's Correspondence Half-a-Mind 1",  -- Cruller_HAM1
    [7792727] = "Cruller's Correspondence Memory Vault 1",  -- Cruller_MemoryVault1
    [7792728] = "Cruller's Correspondence Hatbox Tag",  -- Cruller_Hatbox_Tag
    [7792729] = "Cruller's Correspondence Hatbox",  -- Cruller_Hatbox
    [7792730] = "Tomb of the Sharkophagus (Half-a-Mind)",  -- Tomb_HAM1
    [7792731] = "Tomb of the Sharkophagus (Memory Vault)",  -- Tomb_MemoryVault1
    [7792732] = "Tomb of the Sharkophagus (Purse Tag)",  -- Tomb_Purse_Tag
    [7792733] = "Tomb of the Sharkophagus (Purse)",  -- Tomb_Purse
    [7792734] = "Bob's Bottles Nugget of Wisdom 1",  -- Bob_Nugget1
    [7792735] = "Bob's Bottles Nugget of Wisdom 2",  -- Bob_Nugget2
    [7792736] = "Bob's Bottles Half-a-Mind 1",  -- Bob_HAM1
    [7792737] = "Bob's Bottles Half-a-Mind 2",  -- Bob_HAM2
    [7792738] = "Bob's Bottles Memory Vault 1",  -- Bob_MemoryVault1
    [7792739] = "Bob's Bottles Memory Vault 2",  -- Bob_MemoryVault2
    [7792740] = "Bob's Bottles Suitcase Tag",  -- Bob_Suitcase_Tag
    [7792741] = "Bob's Bottles Hatbox Tag",  -- Bob_Hatbox_Tag
    [7792742] = "Bob's Bottles Purse Tag",  -- Bob_Purse_Tag
    [7792743] = "Bob's Bottles Steamer Trunk Tag",  -- Bob_SteamerTrunk_Tag
    [7792744] = "Bob's Bottles Dufflebag Tag",  -- Bob_Dufflebag_Tag
    [7792745] = "Bob's Bottles Suitcase",  -- Bob_Suitcase
    [7792746] = "Bob's Bottles Hatbox",  -- Bob_Hatbox
    [7792747] = "Bob's Bottles Purse",  -- Bob_Purse
    [7792748] = "Bob's Bottles Steamer Trunk",  -- Bob_SteamerTrunk
    [7792749] = "Bob's Bottles Dufflebag",  -- Bob_Dufflebag
    [7792750] = "Cassie's Collection Nugget of Wisdom 1",  -- Cassie_Nugget1
    [7792751] = "Cassie's Collection Nugget of Wisdom 2",  -- Cassie_Nugget2
    [7792752] = "Cassie's Collection Nugget of Wisdom 3",  -- Cassie_Nugget3
    [7792753] = "Cassie's Collection Nugget of Wisdom 4",  -- Cassie_Nugget4
    [7792754] = "Cassie's Collection Half-a-Mind 1",  -- Cassie_HAM1
    [7792755] = "Cassie's Collection Half-a-Mind 2",  -- Cassie_HAM2
    [7792756] = "Cassie's Collection Memory Vault 1",  -- Cassie_MemoryVault1
    [7792757] = "Cassie's Collection Memory Vault 2",  -- Cassie_MemoryVault2
    [7792758] = "Cassie's Collection Suitcase Tag",  -- Cassie_Suitcase_Tag
    [7792759] = "Cassie's Collection Hatbox Tag",  -- Cassie_Hatbox_Tag
    [7792760] = "Cassie's Collection Purse Tag",  -- Cassie_Purse_Tag
    [7792761] = "Cassie's Collection Steamer Trunk Tag",  -- Cassie_SteamerTrunk_Tag
    [7792762] = "Cassie's Collection Dufflebag Tag",  -- Cassie_Dufflebag_Tag
    [7792763] = "Cassie's Collection Suitcase",  -- Cassie_Suitcase
    [7792764] = "Cassie's Collection Hatbox",  -- Cassie_Hatbox
    [7792765] = "Cassie's Collection Purse",  -- Cassie_Purse
    [7792766] = "Cassie's Collection Steamer Trunk",  -- Cassie_SteamerTrunk
    [7792767] = "Cassie's Collection Dufflebag",  -- Cassie_Dufflebag
    [7792768] = "Lucrecia's Lament Nugget of Wisdom 1",  -- Lucy_Nugget1
    [7792769] = "Lucrecia's Lament Nugget of Wisdom 2",  -- Lucy_Nugget2
    [7792770] = "Lucrecia's Lament Nugget of Wisdom 3",  -- Lucy_Nugget3
    [7792771] = "Lucrecia's Lament Memory Vault 1",  -- Lucy_MemoryVault1
    [7792772] = "Lucrecia's Lament Memory Vault 2",  -- Lucy_MemoryVault2
    [7792773] = "Lucrecia's Lament Suitcase Tag",  -- Lucy_Suitcase_Tag
    [7792774] = "Lucrecia's Lament Hatbox Tag",  -- Lucy_Hatbox_Tag
    [7792775] = "Lucrecia's Lament Purse Tag",  -- Lucy_Purse_Tag
    [7792776] = "Lucrecia's Lament Steamer Trunk Tag",  -- Lucy_SteamerTrunk_Tag
    [7792777] = "Lucrecia's Lament Dufflebag Tag",  -- Lucy_Dufflebag_Tag
    [7792778] = "Lucrecia's Lament Suitcase",  -- Lucy_Suitcase
    [7792779] = "Lucrecia's Lament Hatbox",  -- Lucy_Hatbox
    [7792780] = "Lucrecia's Lament Purse",  -- Lucy_Purse
    [7792781] = "Lucrecia's Lament Steamer Trunk",  -- Lucy_SteamerTrunk
    [7792782] = "Lucrecia's Lament Dufflebag",  -- Lucy_Dufflebag
    [7792783] = "Fatherland Follies Nugget of Wisdom 1",  -- Nick_Nugget1
    [7792784] = "Fatherland Follies Nugget of Wisdom 2",  -- Nick_Nugget2
    [7792785] = "Fatherland Follies Nugget of Wisdom 3",  -- Nick_Nugget3
    [7792786] = "Fatherland Follies Half-a-Mind 1",  -- Nick_HAM1
    [7792787] = "Fatherland Follies Half-a-Mind 2",  -- Nick_HAM2
    [7792788] = "Fatherland Follies Memory Vault 1",  -- Nick_MemoryVault1
    [7792789] = "Fatherland Follies Memory Vault 2",  -- Nick_MemoryVault2
    [7792790] = "Fatherland Follies Suitcase Tag",  -- Nick_Suitcase_Tag
    [7792791] = "Fatherland Follies Hatbox Tag",  -- Nick_Hatbox_Tag
    [7792792] = "Fatherland Follies Purse Tag",  -- Nick_Purse_Tag
    [7792793] = "Fatherland Follies Steamer Trunk Tag",  -- Nick_SteamerTrunk_Tag
    [7792794] = "Fatherland Follies Dufflebag Tag",  -- Nick_Dufflebag_Tag
    [7792795] = "Fatherland Follies Suitcase",  -- Nick_Suitcase
    [7792796] = "Fatherland Follies Hatbox",  -- Nick_Hatbox
    [7792797] = "Fatherland Follies Purse",  -- Nick_Purse
    [7792798] = "Fatherland Follies (Steamer Trunk)",  -- Nick_SteamerTrunk
    [7792799] = "Fatherland Follies (Dufflebag)",  -- Nick_Dufflebag
    [7792800] = "Saphire Lev Ball",  -- Saphire_LevBall
    [7792801] = "Emerald Lev Ball",  -- Emerald_LevBall
    [7792802] = "Ruby Lev Ball",  -- Ruby_LevBall
    [7792803] = "Cannonball",  -- Cannonball
    [7792804] = "Gag Order",  -- GagOrder
    [7792805] = "Pixel Pal",  -- PixelPal
    [7792806] = "Psi Clone",  -- PsiClone
    [7792807] = "Wastepaper",  -- Wastepaper
    [7792808] = "Food for Thought",  -- FoodForThought
    [7792809] = "Heavy Thought",  -- HeavyThought
    [7792810] = "Mental Tax",  -- MentalTax
    [7792811] = "Brain Drain",  -- BrainDrain
    [7792812] = "Mental Block",  -- MentalBlock
    [7792813] = "Speed Reader",  -- SpeedReader
    [7792814] = "Rainblows",  -- Rainblows
    [7792815] = "Strike-onaut",  -- Strike-onaut
    [7792816] = "Bobby Pin",  -- BobbyPin
    [7792817] = "Mental Magnet",  -- MentalMagnet
    [7792818] = "Goo Proof",  -- GooProof
    [7792819] = "Glass Cannon",  -- GlassCannon
    [7792820] = "VIP Discount",  -- VIPDiscount
    [7792821] = "Psimultanium",  -- Psimultanium
    [7792822] = "Stun Gun",  -- StunGun
    [7792823] = "Censory Overload",  -- CensoryOverload
    [7792824] = "Chain Gain",  -- ChainGain
    [7792825] = "Fever Reducer",  -- FeverReducer
    [7792826] = "Goonades",  -- Goonades
    [7792827] = "Beastmastery",  -- Beastmastery
    [7792828] = "Power Nap",  -- PowerNap
    [7792829] = "Plucky",  -- Plucky
    [7792830] = "Time Warp",  -- TimeWarp
    [7792831] = "Bubble Wrap",  -- BubbleWrap
    [7792832] = "Big Time",  -- BigTime
    [7792833] = "Psi Core",  -- PsiCore
    [7792834] = "Psi Pop",  -- PsiPop
    [7792835] = "Dream Fluff",  -- DreamFluff
    [7792836] = "Progressive Carry Capacity",  -- MindsEyelets
    [7792838] = "Progressive Fluff Pouch",  -- FluffPockets
    [7792840] = "Progressive Wallet",  -- PsifoldWallet
    [7792842] = "Psitonium",  -- Psitonium
    [7792843] = "Achromatizer",  -- Achromatizer
    [7792844] = "Classif-eyed",  -- Classif-eyed
    [7792845] = "Hot Dog Spectralizer",  -- HotDogSpectralizer
    [7792846] = "Psychodelica",  -- Psychodelica
    [7792847] = "Otto-Spot",  -- Otto-Spot
    [7792848] = "Thought Tuner",  -- ThoughtTuner
    [7792849] = "Otto-Shot",  -- Otto-Shot
    [7792850] = "Rank Point 1",  -- Rank_Point1
    [7792851] = "Rank Point 2",  -- Rank_Point2
    [7792852] = "Rank Point 3",  -- Rank_Point3
    [7792853] = "Rank Point 4",  -- Rank_Point4
    [7792854] = "Rank Point 5",  -- Rank_Point5
    [7792855] = "Rank Point 6",  -- Rank_Point6
    [7792856] = "Rank Point 7",  -- Rank_Point7
    [7792857] = "Rank Point 8",  -- Rank_Point8
    [7792858] = "Rank Point 9",  -- Rank_Point9
    [7792859] = "Rank Point 10",  -- Rank_Point10
    [7792860] = "Rank Point 11",  -- Rank_Point11
    [7792861] = "Rank Point 12",  -- Rank_Point12
    [7792862] = "Rank Point 13",  -- Rank_Point13
    [7792863] = "Rank Point 14",  -- Rank_Point14
    [7792864] = "Rank Point 15",  -- Rank_Point15
    [7792865] = "Rank Point 16",  -- Rank_Point16
    [7792866] = "Rank Point 17",  -- Rank_Point17
    [7792867] = "Rank Point 18",  -- Rank_Point18
    [7792868] = "Rank Point 19",  -- Rank_Point19
    [7792869] = "Rank Point 20",  -- Rank_Point20
    [7792870] = "Rank Point 21",  -- Rank_Point21
    [7792871] = "Rank Point 22",  -- Rank_Point22
    [7792872] = "Rank Point 23",  -- Rank_Point23
    [7792873] = "Rank Point 24",  -- Rank_Point24
    [7792874] = "Rank Point 25",  -- Rank_Point25
    [7792875] = "Rank Point 26",  -- Rank_Point26
    [7792876] = "Rank Point 27",  -- Rank_Point27
    [7792877] = "Rank Point 28",  -- Rank_Point28
    [7792878] = "Rank Point 29",  -- Rank_Point29
    [7792879] = "Rank Point 30",  -- Rank_Point30
    [7792880] = "Rank Point 31",  -- Rank_Point31
    [7792881] = "Rank Point 32",  -- Rank_Point32
    [7792882] = "Rank Point 33",  -- Rank_Point33
    [7792883] = "Rank Point 34",  -- Rank_Point34
    [7792884] = "Rank Point 35",  -- Rank_Point35
    [7792885] = "Rank Point 36",  -- Rank_Point36
    [7792886] = "Rank Point 37",  -- Rank_Point37
    [7792887] = "Rank Point 38",  -- Rank_Point38
    [7792888] = "Rank Point 39",  -- Rank_Point39
    [7792889] = "Rank Point 40",  -- Rank_Point40
    [7792890] = "Rank Point 41",  -- Rank_Point41
    [7792891] = "Rank Point 42",  -- Rank_Point42
    [7792892] = "Rank Point 43",  -- Rank_Point43
    [7792893] = "Rank Point 44",  -- Rank_Point44
    [7792894] = "Rank Point 45",  -- Rank_Point45
    [7792895] = "Rank Point 46",  -- Rank_Point46
    [7792896] = "Rank Point 47",  -- Rank_Point47
    [7792897] = "Rank Point 48",  -- Rank_Point48
    [7792898] = "Rank Point 49",  -- Rank_Point49
    [7792899] = "Rank Point 50",  -- Rank_Point50
    [7792900] = "Rank Point 51",  -- Rank_Point51
    [7792901] = "Rank Point 52",  -- Rank_Point52
    [7792902] = "Rank Point 53",  -- Rank_Point53
    [7792903] = "Rank Point 54",  -- Rank_Point54
    [7792904] = "Rank Point 55",  -- Rank_Point55
    [7792905] = "Rank Point 56",  -- Rank_Point56
    [7792906] = "Rank Point 57",  -- Rank_Point57
    [7792907] = "Rank Point 58",  -- Rank_Point58
    [7792908] = "Rank Point 59",  -- Rank_Point59
    [7792909] = "Rank Point 60",  -- Rank_Point60
    [7792910] = "Rank Point 61",  -- Rank_Point61
    [7792911] = "Rank Point 62",  -- Rank_Point62
    [7792912] = "Rank Point 63",  -- Rank_Point63
    [7792913] = "Rank Point 64",  -- Rank_Point64
    [7792914] = "Rank Point 65",  -- Rank_Point65
    [7792915] = "Rank Point 66",  -- Rank_Point66
    [7792916] = "Rank Point 67",  -- Rank_Point67
    [7792917] = "Rank Point 68",  -- Rank_Point68
    [7792918] = "Rank Point 69",  -- Rank_Point69
    [7792919] = "Rank Point 70",  -- Rank_Point70
    [7792920] = "Rank Point 71",  -- Rank_Point71
    [7792921] = "Rank Point 72",  -- Rank_Point72
    [7792922] = "Rank Point 73",  -- Rank_Point73
    [7792923] = "Rank Point 74",  -- Rank_Point74
    [7792924] = "Rank Point 75",  -- Rank_Point75
    [7792925] = "Rank Point 76",  -- Rank_Point76
    [7792926] = "Rank Point 77",  -- Rank_Point77
    [7792927] = "Rank Point 78",  -- Rank_Point78
    [7792928] = "Rank Point 79",  -- Rank_Point79
    [7792929] = "Rank Point 80",  -- Rank_Point80
    [7792930] = "Rank Point 81",  -- Rank_Point81
    [7792931] = "Rank Point 82",  -- Rank_Point82
    [7792932] = "Rank Point 83",  -- Rank_Point83
    [7792933] = "Rank Point 84",  -- Rank_Point84
    [7792934] = "Rank Point 85",  -- Rank_Point85
    [7792935] = "Rank Point 86",  -- Rank_Point86
    [7792936] = "Rank Point 87",  -- Rank_Point87
    [7792937] = "Rank Point 88",  -- Rank_Point88
    [7792938] = "Rank Point 89",  -- Rank_Point89
    [7792939] = "Rank Point 90",  -- Rank_Point90
    [7792940] = "Rank Point 91",  -- Rank_Point91
    [7792941] = "Rank Point 92",  -- Rank_Point92
    [7792942] = "Rank Point 93",  -- Rank_Point93
    [7792943] = "Rank Point 94",  -- Rank_Point94
    [7792944] = "Rank Point 95",  -- Rank_Point95
    [7792945] = "Rank Point 96",  -- Rank_Point96
    [7792946] = "Rank Point 97",  -- Rank_Point97
    [7792947] = "Rank Point 98",  -- Rank_Point98
    [7792948] = "Rank Point 99",  -- Rank_Point99
    [7792949] = "Rank Point 100",  -- Rank_Point100
    [7792950] = "Rank Point 101",  -- Rank_Point101
    [7792951] = "Rank Point 102",  -- Rank_Point102
    [7792952] = "Intern Sticker",  -- Motherlobe_Access
    [7792953] = "Thinkerprint Full Access",  -- Quarry_Access
    [7792954] = "Questionable Area Access",  -- QA_Access
    [7792955] = "Green Needle Gulch Access",  -- GNG_Access
    [7792956] = "Loboto's Labrynth Access",  -- Loboto_Access
    [7792958] = "Hollis' Classroom Access",  -- HC_Access
    [7792960] = "Hollis' Hot Streak Access",  -- HH_Access
    [7792962] = "Compton's Cookoff Access",  -- Compton_Access
    [7792964] = "Psi King's Sensorium Access",  -- PsiKing_Access
    [7792966] = "Ford's Follicles Access",  -- Ford_Access
    [7792968] = "Strike City Access",  -- StrikeCity_Access
    [7792970] = "Cruller's Correspondence Access",  -- Cruller_Access
    [7792972] = "Tomb of the Sharkophagus Access",  -- Tomb_Access
    [7792974] = "Bob's Bottles Access",  -- Bob_Access
    [7792976] = "Cassie's Collection Access",  -- Cassie_Access
    [7792978] = "Lucrecia's Lament Access",  -- Lucy_Access
    [7792980] = "Fatherland Follies Access",  -- Nick_Access
    [7792984] = "Melee - Base Power",  -- Melee
    [7792985] = "Melee - Dodge Attack",  -- Melee_Upgrade1
    [7792986] = "Melee - Slap Happy",  -- Melee_Upgrade2
    [7792987] = "Melee - Shockwave",  -- Melee_Upgrade3
    [7792988] = "Progressive Telekinesis",  -- Telekinesis
    [7792992] = "Progressive Psi Blast",  -- PsiBlast
    [7792996] = "Progressive Pyrokinesis",  -- Pyrokinesis
    [7793000] = "Progressive Levitation",  -- Levitation
    [7793004] = "Progressive Clairvoyance",  -- Clairvoyance
    [7793008] = "Progressive Mental Connection",  -- MentalConnection
    [7793012] = "Progressive Time Bubble",  -- TimeBubble
    [7793016] = "Progressive Projection",  -- Projection
    [7793020] = "Senior League Card",  -- Senior_League_Card
    [7793021] = "Psitanium x25",  -- Psitanium_25
    [7793022] = "Psitanium x50",  -- Psitanium_50
    [7793023] = "Psitanium x100",  -- Psitanium_100
    [7793024] = "Normal Outfit",  -- Normal_Outfit
}

-- ---------------------------------------------------------------------------
-- Ability tier tracking (runtime state, cleared on new session)
-- ---------------------------------------------------------------------------

Items.ability_tiers = {
    ["Progressive Telekinesis"]       = 0,
    ["Progressive Psi Blast"]         = 0,
    ["Progressive Pyrokinesis"]       = 0,
    ["Progressive Levitation"]        = 0,
    ["Progressive Clairvoyance"]      = 0,
    ["Progressive Mental Connection"] = 0,
    ["Progressive Time Bubble"]       = 0,
    ["Progressive Projection"]        = 0,
    ["Progressive Carry Capacity"]    = 0,
    ["Progressive Fluff Pouch"]       = 0,
    ["Progressive Wallet"]            = 0,
}

-- Maps progressive display name → ability tag used by the game.
Items.ability_tags = {
    ["Progressive Telekinesis"]       = "Ability.Telekinesis",
    ["Progressive Psi Blast"]         = "Ability.PsiBlast",
    ["Progressive Pyrokinesis"]       = "Ability.Pyrokinesis",
    ["Progressive Levitation"]        = "Ability.Levitation",
    ["Progressive Clairvoyance"]      = "Ability.Clairvoyance",
    ["Progressive Mental Connection"] = "Ability.MentalConnection",
    ["Progressive Time Bubble"]       = "Ability.TimeBubble",
    ["Progressive Projection"]        = "Ability.Projection",
}

-- Maps progressive display name → inventory upgrade function name.
Items.equipment_funcs = {
    ["Progressive Carry Capacity"] = "UpgradeCarryCapacity",
    ["Progressive Fluff Pouch"]    = "UpgradeFluffPouch",
    ["Progressive Wallet"]         = "UpgradeWallet",
}

-- ---------------------------------------------------------------------------
-- Area access item → save-game flag name
-- ---------------------------------------------------------------------------

Items.area_flags = {
    ["Intern Sticker"]                        = "bMotherlobe_Unlocked",
    ["Thinkerprint Full Access"]              = "bQuarry_Unlocked",
    ["QA Access Pass"]                        = "bQA_Unlocked",
    ["GNG Access Pass"]                       = "bGNG_Unlocked",
    ["Loboto Access Pass"]                    = "bLoboto_Unlocked",
    ["Hollis Classroom Access Pass"]          = "bHC_Unlocked",
    ["Hollis Hot Streak Access Pass"]         = "bHH_Unlocked",
    ["Compton Cookoff Access Pass"]           = "bCompton_Unlocked",
    ["Psi King Sensorium Access Pass"]        = "bPsiKing_Unlocked",
    ["Fords Follicles Access Pass"]           = "bFord_Unlocked",
    ["Strike City Access Pass"]               = "bStrikeCity_Unlocked",
    ["Crullers Correspondence Access Pass"]   = "bCruller_Unlocked",
    ["Tomb of the Sharkophagus Access Pass"]  = "bTomb_Unlocked",
    ["Bobs Bottles Access Pass"]              = "bBob_Unlocked",
    ["Cassies Collection Access Pass"]        = "bCassie_Unlocked",
    ["Lucrecias Lament Access Pass"]          = "bLucy_Unlocked",
    ["Fatherland Follies Access Pass"]        = "bNick_Unlocked",
}

-- ---------------------------------------------------------------------------
-- Outfit → in-game outfit ID
-- ---------------------------------------------------------------------------

Items.outfit_ids = {
    ["Normal Outfit"]  = 0,
    ["Tried and True"] = 1,
    ["Circus Skivvies"]= 2,
    ["Suit"]           = 3,
}

-- ---------------------------------------------------------------------------
-- Grant dispatcher
-- ---------------------------------------------------------------------------

--- Grant an item by its AP item ID.
---@param item_id number  AP item ID
function Items.grant(item_id)
    local name = Items.id_to_name[item_id]
    if not name then
        print("[AP] WARNING: Unknown item ID " .. tostring(item_id))
        return
    end
    print("[AP] Granting item: " .. name .. " (id=" .. tostring(item_id) .. ")")

    if Items.ability_tiers[name] ~= nil and Items.ability_tags[name] then
        Items._grant_progressive_ability(name)
    elseif Items.ability_tiers[name] ~= nil and Items.equipment_funcs[name] then
        Items._grant_progressive_equipment(name)
    elseif Items.area_flags[name] then
        Items._grant_area_access(name)
    elseif Items.outfit_ids[name] ~= nil then
        Items._grant_outfit(name)
    else
        Items._grant_generic_item(name, item_id)
    end
end

-- ---------------------------------------------------------------------------
-- Internal grant helpers
-- ---------------------------------------------------------------------------

function Items._grant_progressive_ability(prog_name)
    local current   = Items.ability_tiers[prog_name]
    local next_tier = current + 1
    if next_tier > 4 then
        print("[AP] " .. prog_name .. " already at max tier (4)")
        return
    end
    Items.ability_tiers[prog_name] = next_tier

    local tag = Items.ability_tags[prog_name]
    local raz = Items._get_raz()
    if raz then
        local ok, err = pcall(function()
            raz.PsychicsComponent:SetAbilityTier(tag, next_tier)
        end)
        if not ok then
            local gi = Items._get_game_instance()
            if gi then pcall(function() gi:GrantAbility(tag, next_tier) end) end
            print("[AP] Ability grant fallback used: " .. tostring(err))
        end
    end
end

--- Re-apply a progressive ability to a specific saved tier without incrementing
--- the counter.  Used on connect to restore ability levels after a game-save
--- reset — analogous to OpenTTD v1.2.2's infrastructure-unlock re-apply fix.
function Items._reapply_ability(prog_name, tier)
    if tier <= 0 then return end
    local tag = Items.ability_tags[prog_name]
    if not tag then return end
    Items.ability_tiers[prog_name] = tier
    local raz = Items._get_raz()
    if raz then
        local ok, err = pcall(function()
            raz.PsychicsComponent:SetAbilityTier(tag, tier)
        end)
        if not ok then
            local gi = Items._get_game_instance()
            if gi then pcall(function() gi:GrantAbility(tag, tier) end) end
            print("[AP] Ability reapply fallback used for " .. prog_name .. ": " .. tostring(err))
        end
    end
end

function Items._grant_progressive_equipment(prog_name)
    local current   = Items.ability_tiers[prog_name]
    local next_tier = current + 1
    if next_tier > 2 then
        print("[AP] " .. prog_name .. " already at max tier (2)")
        return
    end
    Items.ability_tiers[prog_name] = next_tier
    local func_name = Items.equipment_funcs[prog_name]
    local raz = Items._get_raz()
    if raz then
        pcall(function()
            raz.InventoryComponent[func_name](raz.InventoryComponent, next_tier)
        end)
    end
end

function Items._grant_area_access(item_name)
    local flag = Items.area_flags[item_name]
    local gi = Items._get_game_instance()
    if gi then
        pcall(function()
            gi.SaveGame[flag] = true
            gi:SaveCurrentGame()
        end)
    end
    local raz = Items._get_raz()
    if raz then pcall(function() raz:UnlockArea(flag) end) end
end

function Items._grant_outfit(item_name)
    local outfit_id = Items.outfit_ids[item_name]
    local raz = Items._get_raz()
    if raz then pcall(function() raz:SetOutfit(outfit_id) end) end
end

function Items._grant_generic_item(item_name, item_id)
    local raz = Items._get_raz()
    if not raz then return end

    if item_name == "Psitanium x25" then
        pcall(function() raz:AddPsitanium(25) end)
    elseif item_name == "Psitanium x50" then
        pcall(function() raz:AddPsitanium(50) end)
    elseif item_name == "Psitanium x100" then
        pcall(function() raz:AddPsitanium(100) end)
    elseif item_name == "PsiCore" then
        pcall(function() raz:AddPsiCore(1) end)
    elseif item_name == "PsiPop" then
        pcall(function() raz:AddPsiPop(1) end)
    elseif item_name == "DreamFluff" then
        pcall(function() raz:AddDreamFluff(1) end)
    elseif item_name == "Melee - Base Power" then
        -- Always precollected; no-op if received again
    elseif item_name == "Senior League Card" then
        local gi = Items._get_game_instance()
        if gi then pcall(function() gi.SaveGame.bSeniorLeagueCard = true end) end
    elseif item_name == "Thought Tuner" then
        local gi = Items._get_game_instance()
        if gi then pcall(function() gi.SaveGame.bThoughtTuner = true end) end
    elseif item_name == "Otto-Shot" then
        pcall(function() raz:AddOttoShot(1) end)
    else
        pcall(function() raz:AddInventoryItemByName(item_name) end)
    end
end

-- ---------------------------------------------------------------------------
-- UE4 object helpers
-- ---------------------------------------------------------------------------

function Items._get_raz()
    local raz = nil
    pcall(function()
        raz = UE4SS.GetPlayerCharacter()
        if not raz then raz = FindFirstOf("BP_Raz_C") end
    end)
    return raz
end

function Items._get_game_instance()
    local gi = nil
    pcall(function()
        gi = UE4SS.GetGameInstance()
        if not gi then gi = FindFirstOf("Psychonauts2GameInstance_C") end
    end)
    return gi
end

return Items

